### PR TITLE
Fix `e_preview` normalization

### PR DESCRIPTION
**Pull request by adimiz1**
### Root Cause
Normalize function for expression changed variables such as: `duration`

### Implementation
The :${it} part is to prevent normalization of vars with a preceding colon (such as :duration)

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [ ] New feature
- [x] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [x] Yes
- [ ] No

#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I ran the full test suite before pushing the changes and all the tests pass.

### CODE REVIEW

**Review by patrick-tolosa — CHANGES_REQUESTED** [review]
Please include a test in the PR.

We can consider adding a test file like this one (if it doesn't exist in Kotlin already)

https://github.com/cloudinary/js-url-gen/blob/master/__TESTS__/unit/expression.test.ts

**Review by const-cloudinary — CHANGES_REQUESTED** [review]
Totally agree with @patrick-tolosa :)

**Comment by adimiz1** [comment]
@patrick-tolosa regarding the link you attached it answered another problem needs to be solved, where variable names using $ are getting normlized , but that's a different PR , I agree we should add all those test cases.

**Review by patrick-tolosa — APPROVED** [review]

**Review by const-cloudinary — CHANGES_REQUESTED** [review]
The PR itself looks great! Let's just change the title/commit message to something like
`Fix expression normalization`

The fix affects all expressions (not only `preview`)

**Review by const-cloudinary — APPROVED** [review]

**Pull request merged**
